.Dd September 26, 2021
.Dt ECHOBOX 1
.Os
.Sh NAME
.Nm echobox
.Nd write arguments in a box to the standard output
.Sh SYNOPSIS
.Nm
.Op Fl a|--align Ar name
.Op Fl b|--basic-char Ar char
.Op Fl f|--fill-char Ar char
.Op Fl i|--inter-lines Ar number
.Op Fl l|--lead-lines Ar number
.Op Fl S|--style Ar name
.Op Fl s|--spaces Ar number
.Op Fl t|--trail-lines Ar number
.Op Fl -debug
.Op Fl -help|-?
.Op Fl -version
.Op Fl -
.Op Ar "string ..."
.Sh DESCRIPTION
The
.Nm
utility writes any specified operands, separated by single blank (' ') characters, in a box, to the standard output.
The "\\n" substring is used to split the concatenated operands into multiple lines.
.Pp
If there are no arguments provided on the command line, standard input is read.
.Ss OPTIONS
.Op Fl a|--align Ar name
Sets the alignment to use.
Possible values: left (default), center, middle, right.
.Pp
.Op Fl b|--basic-char Ar char
Sets the character to use with the basic style.
Default value: '#'.
.Pp
.Op Fl f|--fill-char Ar char
Sets the character to use to fill the box.
Default value: ' '.
.Pp
.Op Fl i|--inter-lines Ar number
Sets the number of lines separating the text from the box on the top and bottom sides.
Default value: 1.
.Pp
.Op Fl l|--lead-lines Ar number
Sets the number of blank lines preceding the box.
Default value: 0.
.Pp
.Op Fl S|--style Ar name
Sets the style to use.
Possible values: basic (default), ascii, single, curved, hatched, double, block.
.Pp
.Op Fl s|--spaces Ar number
Sets the number of spaces separating the text from the box on the left and right sides.
Default value: 3.
.Pp
.Op Fl t|--trail-lines Ar number
Sets the number of blank lines following the box.
Default value: 1.
.Pp
.Op Fl -debug
Enable debug mode
.Pp
.Op Fl -help|-?
Print usage and this help message and exit
.Pp
.Op Fl -version
Print version and exit
.Pp
.Op Fl -
Options processing terminator.
Contrarily to the echo(1) command, it is recognized as such.
.Sh ENVIRONMENT
Environment variables are processed first and thus overridden by command line options.
.Pp
.Ev ECHOBOX_STYLE
Sets the style to use.
.Pp
.Ev ECHOBOX_ALIGN
Sets the alignment to use.
.Pp
.Ev ECHOBOX_BASIC_CHAR
Sets the character to use with the basic style.
.Pp
.Ev ECHOBOX_FILL_CHAR
Sets the character to use to fill the box.
.Pp
.Ev ECHOBOX_SPACES
Sets the number of spaces separating the text from the box on the left and right sides.
.Pp
.Ev ECHOBOX_INTER_LINES
Sets the number of lines separating the text from the box on the top and bottom sides.
.Pp
.Ev ECHOBOX_LEAD_LINES
Sets the number of blank lines preceding the box.
.Pp
.Ev ECHOBOX_TRAIL_LINES
Sets the number of blank lines following the box.
.Pp
.Ev ECHOBOX_DEBUG
Enable debug level messages.
.Pp
.Ev COLUMNS
Defines the number of columns in the terminal window.
This variable is sometimes provided by the Bash shell and some others, but not necessarily exported.
It's used for center and right alignments.
Default value: 80.
.Sh EXIT STATUS
.Ex -std echobox
.Sh SEE ALSO
.Xr dialog 1 ,
.Xr fortune 6 
.Pp
.Lk https://en.wikipedia.org/wiki/Box-drawing_character
.Pp
.Lk https://unicode-table.com/fr/#box-drawing
.Sh STANDARDS
The
.Nm
command is not a standard UNIX/POSIX command.
.Pp
It tries to follow the PEP 8 style guide for Python code.
.Sh PORTABILITY
Tested OK under Windows, though some of the styles are not available
(the hatched and curved Unicode characters are not fully recognized in the cmd.exe and PowerShell command prompts).
.Sh HISTORY
The
.Nm
command was created as an example for the
.Lk https://github.com/HubTou/PNU PNU project
demonstrating how to process the environment and the command line, and use the Python logging module.
.Pp
It's also used as a filter for
.Xr fortune 6 
output, in order to introduce some boxology.
.Sh LICENSE
This utility is available under the 3-clause BSD license.
.Sh AUTHORS
Hubert Tournier
.Sh BUGS
Specifying basic or fill Unicode characters is not currently possible with the environment and command line options.
.Pp
Display will overflow if your text is wider than your console.
